from django.urls import path,re_path  
from . import views,administradorviews,tutorviews,veterinarioviews

urlpatterns = [
    path('', views.inicio, name='inicio'),
    re_path(r'^crear-usuario/?$', views.crearUsuario, name='crearusuario'),
    re_path(r'^search_id/(?P<id_externo>[A-Za-z0-9]+)/$', views.mascotaSOS, name='search_id'),
    re_path(r'^tag_SOS/(?P<id_externo>[A-Za-z0-9]+)/$',views.MyProfile, name='tag_SOS'),
    re_path(r'^sendnotification/?$', views.SendNotification, name='sendnotification'),
    re_path(r'^allrazastipomascota/(?P<tipoId>[0-9]+)', views.allRazasTipoMascota, name='allrazastipomascota'),
    re_path(r'^assess_upload/?$', views.upload_images, name='assess_upload'),
    re_path(r'^eliminar_imagen/?$', views.delete_img_path, name='eliminar_imagen'),
    re_path(r'^validarQR/?$', views.validarQR, name='validarQR'),
    re_path(r'^crear-veterinario/?$', views.crearveterinario, name='crearveterinario'),
    re_path(r'^login/?$', views.django_login_view, name='login'),
    re_path(r'^prelogin/?$', views.django_prelogin_view, name='prelogin'),
    re_path(r'^preregistro/?$', views.preregistro, name='preregistro'),
    re_path(r'^html/personal/?$', views.personal, name='personal'),
    re_path(r'^productos/(?P<number>[0-9]+)', views.productos, name='pro'),
    re_path(r'^crear_mascota/?$', views.crear_mascota, name='crear_mascota'),
    re_path(r'^nosotros/?$', views.nosotros, name='nosotros'),
    re_path(r'^administrar/veterinarios/?$',administradorviews.administradorve, name='adveterinarios'),
    re_path(r'^logout/?$',views.logout, name='logout'),
    re_path(r'^login_recuperar/?$',views.login_recuperar, name='login_recuperar'),
    re_path(r'^recuperar/?$',views.recuperar, name='recuperar'),
    re_path(r'^politicas/?$',views.politicas, name='politicas'),
    re_path(r'^administrador/?$',administradorviews.administrador, name='administrador'),
    re_path(r'^administrador/vusuarios/?$',administradorviews.vusuarios, name='vusuarios'),
    re_path(r'^administrador/vveterinarios/?$',administradorviews.vveterinarios, name='vveterinarios'),
    re_path(r'^administrador/vpoliticas/?$',administradorviews.mostrar_politicas, name='vpoliticas'),
    re_path(r'^administrador/vmascotas/?$',administradorviews.vmascotas, name='vmascotas'),
    re_path(r'^administrador/vpromociones/?$',administradorviews.mostrar_promociones, name='vpromociones'),
    re_path(r'^administrador/promociones-crear/?$',administradorviews.promociones_crear, name='promociones-crear'),
    re_path(r'^administrador/promociones-actualizar/(?P<promocione_id>[0-9]+)', administradorviews.promociones_actualizar, name='promociones-actualizar'),
    re_path(r'^administrador/promociones-eliminar/(?P<promocione_id>[0-9]+)', administradorviews.promociones_eliminar, name='promociones-eliminar'),
    re_path(r'^administrador/vbanner/?$',administradorviews.mostrar_banner, name='mostrar_banner'),
    re_path(r'^administrador/banner-crear/?$',administradorviews.banner_crear, name='banner-crear'),
    re_path(r'^administrador/banner-actualizar/(?P<banner_id>[0-9]+)', administradorviews.banner_actualizar, name='banner-actualizar'),
    re_path(r'^administrador/banner-eliminar/(?P<banner_id>[0-9]+)', administradorviews.banner_eliminar, name='banner-eliminar'),
    re_path(r'^administrador/vimagenes-banner/?$',administradorviews.mostrar_imagenesbanner, name='vimagenes-banner'),
    re_path(r'^administrador/imagenesbanner-crear/?$',administradorviews.imagenesbanner_crear, name='imagenesbanner-crear'),
    re_path(r'^administrador/imagenesbanner-actualizar/(?P<imagenes_banner_id>[0-9]+)', administradorviews.imagenesbanner_actualizar, name='imagenesbanner-actualizar'),
    re_path(r'^administrador/imagenesbanner-eliminar/(?P<imagenes_banner_id>[0-9]+)', administradorviews.imagenesbanner_eliminar, name='imagenesbanner-eliminar'),
    re_path(r'^administrador/vimagenes/?$',administradorviews.mostrar_imagenes, name='vimagenes'),
    re_path(r'^administrador/imagenes-crear/?$',administradorviews.imagenes_crear, name='imagenes-crear'),
    re_path(r'^administrador/imagenes-actualizar/(?P<imagenes_id>[0-9]+)', administradorviews.imagenes_actualizar, name='imagenes-actualizar'),
    re_path(r'^administrador/imagenes-eliminar/(?P<imagenes_id>[0-9]+)', administradorviews.imagenes_eliminar, name='imagenes-eliminar'),
    re_path(r'^administrador/vpreguntas-frecuente/?$',administradorviews.mostrar_preguntas, name='vpreguntas'),
    re_path(r'^administrador/preguntas-crear/?$',administradorviews.preguntas_crear, name='preguntas-crear'),
    re_path(r'^administrador/preguntas-actualizar/(?P<preguntas_id>[0-9]+)', administradorviews.preguntas_actualizar, name='preguntas-actualizar'),
    re_path(r'^administrador/preguntas-eliminar/(?P<preguntas_id>[0-9]+)', administradorviews.preguntas_eliminar, name='preguntas-eliminar'),
    re_path(r'^administrador/politicas-crear/?$',administradorviews.politicas_crear, name='politicas_crear'),
    re_path(r'^administrador/politicas-actualizar/(?P<politica_id>[0-9]+)', administradorviews.politicas_actualizar, name='politicas-actualizar'),
    re_path(r'^administrador/politicas-eliminar/(?P<politica_id>[0-9]+)', administradorviews.politicas_eliminar, name='politicas-eliminar'),
    re_path(r'^administrador/vquienes-somos/?$',administradorviews.mostrar_quienesomos, name='vquienes'),
    re_path(r'^administrador/quienes-somos-crear/?$',administradorviews.quienessomos_crear, name='quienes-somos-crear'),
    re_path(r'^administrador/quienes-somos-actualizar/(?P<quienes_id>[0-9]+)', administradorviews.quienes_actualizar, name='quienes-somos-actualizar'),
    re_path(r'^administrador/quienes-somos-eliminar/(?P<quienes_id>[0-9]+)', administradorviews.quienes_eliminar, name='quienes-somos-eliminar'),
    re_path(r'^administrador/vventas/?$',administradorviews.mostrar_ventas, name='vventas'),
    re_path(r'^administrador/vdetalle-ventas/?$',administradorviews.mostrar_detalleventa, name='vdetalleventas'),
    re_path(r'^administrador/vproductos/?$',administradorviews.mostrar_productos, name='vproductos'),
    re_path(r'^administrador/productos-crear/?$',administradorviews.productos_crear, name='productos-crear'),
    re_path(r'^administrador/productos-actualizar/(?P<productos_id>[0-9]+)', administradorviews.productos_actualizar, name='productos-actualizar'),
    re_path(r'^administrador/productos-eliminar/(?P<productos_id>[0-9]+)', administradorviews.productos_eliminar, name='productos-eliminar'),
    re_path(r'^administrador/informaciones/?$', administradorviews.mandar_informacion, name='informaciones'),
    re_path(r'^administrador/vterminos/?$',administradorviews.mostrar_terminos, name='vterminos'),
    re_path(r'^administrador/terminos-crear/?$',administradorviews.terminos_crear, name='terminos-crear'),
    re_path(r'^administrador/terminos-actualizar/(?P<id>[0-9]+)', administradorviews.termino_actualizar, name='terminos-actualizar'),
    re_path(r'^administrador/terminos-eliminar/(?P<id>[0-9]+)', administradorviews.terminos_eliminar, name='terminos-eliminar'),
    re_path(r'^administrador/vtecnologia/?$',administradorviews.mostrar_tecnologia, name='vtecnologia'),
    re_path(r'^administrador/tecnologia-crear/?$',administradorviews.tecnologia_crear, name='tecnologia-crear'),
    re_path(r'^administrador/tecnologia-actualizar/(?P<id>[0-9]+)', administradorviews.tecnologia_actualizar, name='tecnologia-actualizar'),
    re_path(r'^administrador/tecnologia-eliminar/(?P<id>[0-9]+)', administradorviews.tecnologia_eliminar, name='tecnologia-eliminar'),

    re_path(r'^administrador/cusuarios/?$',administradorviews.cusuarios, name='cusuarios'),
    re_path(r'^administrador/usuarios-actualizar/(?P<id>[0-9]+)', administradorviews.usuarios_actualizar, name='usuarios-actualizar'),
    re_path(r'^administrador/usuarios-eliminar/(?P<id>[0-9]+)', administradorviews.usuarios_eliminar, name='usuarios-eliminar'),
    re_path(r'^administrador/mascotas-crear/?$',administradorviews.mascotas_crear, name='mascotas-crear'),
    re_path(r'^administrador/mascota-actualizar/(?P<id>[0-9]+)', administradorviews.mascota_actualizar, name='mascota-actualizar'),
    re_path(r'^administrador/mascota-eliminar/(?P<id>[0-9]+)', administradorviews.mascota_eliminar, name='mascota-eliminar'),
    
    re_path(r'^activar/(?P<id_usuario>[0-9]+)', views.activar_usuario, name='activar'),
    re_path(r'^desbloquear/(?P<id_usuario>[0-9]+)', views.desbloquear, name='desbloquear'),
    #path('inicio/protected/', views.protected, name='protected'),
    path('preguntas-frecuentes', views.preguntas, name="preguntas"),
    path('terminos-condiciones', views.terminos, name="terminos"),
    path('nuestra-tecnologia', views.nuestra, name="nuestra"),
    path('funcionamiento', views.funcionamiento, name="funcionamiento"),
    path('demo', views.demos3, name="s3"),


    re_path(r'^tutor/Mi-Perfil/?$',tutorviews.perfil, name='perfil'),
    re_path(r'^tutor/Actualizar-Perfil/?$',tutorviews.actualizar_perfil, name='actualizar_perfil'),
    re_path(r'^tutor/actualizar-contrasena/?$',tutorviews.actualizar_contrasena, name='actualizar_contrasena'),
    re_path(r'^tutor/Mis-Mascotas/?$',tutorviews.mostrar_mascotas, name='mascotas'),
    re_path(r'^tutor/crear-mascotas/?$',tutorviews.mascotas_crear, name='crear_mascotas'),
    re_path(r'^tutor/mascota-actualizar/?$', tutorviews.actualizar_mascota, name='actualizar_mascota'),
    re_path(r'^tutor/mascota-eliminar/(?P<id>[0-9]+)', tutorviews.mascota_eliminar, name='eliminar_mascota'),
    re_path(r'^tutor/perfil-mascota/(?P<url>\w+)',tutorviews.MascotaSOS, name='SOS'),


    re_path(r'^veterinario/?$',veterinarioviews.veterinario, name='veterinario'),

    #Veterinario
    re_path(r'^veterinario/?$',veterinarioviews.index, name='veterinario'),


]
handler404 = views.error_404
